# Generated by Django 2.2.5 on 2019-10-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=250)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escenario', models.CharField(max_length=250)),
                ('capacidad_escenario', models.CharField(max_length=250)),
                ('direccion_escenario', models.CharField(max_length=250)),
                ('ciudad_escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escenarios.Ciudad')),
                ('departamento_escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escenarios.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escenarios.Departamento'),
        ),
    ]
