# Generated by Django 2.2.5 on 2019-10-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('asistentes', '0001_initial'),
        ('escenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=250)),
                ('descripcion_evento', models.TextField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=250)),
                ('fecha_inicio_evento', models.DateTimeField(blank=True, null=True)),
                ('fecha_Fin_evento', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='static/uploads/eventos/')),
                ('asitentes', models.ManyToManyField(blank=True, to='asistentes.Attendee')),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escenarios.Ciudad')),
                ('nombre_escenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escenarios.Escenario')),
                ('tickets', models.ManyToManyField(blank=True, to='tickets.Ticket')),
            ],
        ),
    ]
